# Generated by Django 3.0.8 on 2021-05-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQs', '0002_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='tid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
