# Generated by Django 3.0.8 on 2021-05-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQs', '0003_auto_20210511_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
