# Generated by Django 3.0.8 on 2021-05-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQs', '0004_auto_20210511_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('marks', models.IntegerField(default=0)),
            ],
        ),
    ]
